# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-08 18:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amphi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AmphibianTransferUser',
        ),
        migrations.AlterModelOptions(
            name='input',
            options={'permissions': (('view_input', 'Can view inputs'),), 'verbose_name': 'input', 'verbose_name_plural': 'inputs'},
        ),
        migrations.AlterField(
            model_name='input',
            name='by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='by'),
        ),
    ]
