# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-21 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amphi', '0003_auto_20170208_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='input',
            options={'ordering': ['-date'], 'verbose_name': 'input', 'verbose_name_plural': 'inputs'},
        ),
    ]
