# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-07 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'inschrijving', 'verbose_name_plural': 'inschrijvingen'},
        ),
    ]
