# Generated by Django 5.0.1 on 2024-01-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('activities', '0001_initial'), ('activities', '0002_activity_text'), ('activities', '0003_activity_slug'), ('activities', '0004_activity_practical'), ('activities', '0005_auto_20160928_1740'), ('activities', '0006_auto_20160928_1740'), ('activities', '0007_auto_20160928_1744'), ('activities', '0008_auto_20160928_1745'), ('activities', '0009_auto_20160928_1746'), ('activities', '0010_auto_20161207_2126'), ('activities', '0011_auto_20170118_1531'), ('activities', '0012_auto_20170118_1735'), ('activities', '0013_activity_published'), ('activities', '0014_neighboringactivity'), ('activities', '0015_auto_20170326_1215'), ('activities', '0016_auto_20200628_1240'), ('activities', '0017_auto_20200628_1323'), ('activities', '0018_auto_20200628_1333'), ('activities', '0019_auto_20201003_1036')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NeighboringActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('date', models.DateField(verbose_name='date')),
                ('text', models.TextField(verbose_name='text')),
                ('link', models.URLField(verbose_name='link')),
                ('division', models.IntegerField(choices=[(1, 'Boven-Schelde'), (2, 'Scheldeland'), (3, 'Houtem'), (4, 'Zwalmvallei')], verbose_name='division')),
            ],
            options={
                'verbose_name': 'neighboring activity',
                'verbose_name_plural': 'neighboring activities',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('date', models.DateField(verbose_name='date')),
                ('intro', models.TextField(verbose_name='intro')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('practical', models.TextField(verbose_name='practical')),
                ('short', models.TextField(max_length=150, verbose_name='short')),
                ('published', models.BooleanField(default=False, verbose_name='published')),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ['date'],
                'verbose_name': 'activity',
            },
        ),
    ]
