# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-20 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
