# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-28 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='slug',
            field=models.SlugField(default='test-test'),
            preserve_default=False,
        ),
    ]
