# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-28 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='practical',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
