# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-28 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_activity_practical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='text',
            field=models.TextField(max_length=80),
        ),
    ]
