# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-28 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_auto_20160928_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='short',
            field=models.TextField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='text',
            field=models.TextField(),
        ),
    ]
