# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-28 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_auto_20160928_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='short',
            field=models.TextField(max_length=125),
        ),
    ]
