# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-28 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_auto_20160928_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='text',
            new_name='intro',
        ),
    ]
