# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-18 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_auto_20161207_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-date'], 'verbose_name': 'activity', 'verbose_name_plural': 'activities'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='intro',
            field=models.TextField(verbose_name='intro'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='practical',
            field=models.TextField(verbose_name='practical'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='short',
            field=models.TextField(max_length=125, verbose_name='short'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='slug',
            field=models.SlugField(verbose_name='slug'),
        ),
    ]
