# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-18 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_auto_20170118_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='short',
            field=models.TextField(max_length=150, verbose_name='short'),
        ),
    ]
