# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-21 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0012_auto_20170118_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='published',
            field=models.BooleanField(default=False, verbose_name='published'),
        ),
    ]
