# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-26 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0013_activity_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeighboringActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('date', models.DateField(verbose_name='date')),
                ('text', models.TextField(max_length=200, verbose_name='text')),
                ('link', models.URLField(verbose_name='link')),
                ('division', models.IntegerField(choices=[(1, 'Boven-Schelde'), (2, 'Scheldeland'), (3, 'Houtem'), (4, 'Zwalmvallei')], verbose_name='division')),
            ],
            options={
                'verbose_name': 'neighboring activity',
                'verbose_name_plural': 'neighboring activities',
                'ordering': ['-date'],
            },
        ),
    ]
