# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-26 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0014_neighboringactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighboringactivity',
            name='text',
            field=models.TextField(verbose_name='text'),
        ),
    ]
