# Generated by Django 2.2.5 on 2020-06-28 10:40

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0015_auto_20170326_1215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['date'], 'verbose_name': 'activity', 'verbose_name_plural': 'activities'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='intro',
            field=djrichtextfield.models.RichTextField(verbose_name='intro'),
        ),
    ]
