# Generated by Django 2.2.5 on 2020-06-28 11:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0016_auto_20200628_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='practical',
            field=ckeditor.fields.RichTextField(verbose_name='practical'),
        ),
    ]
