# Generated by Django 2.2.5 on 2020-10-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0018_auto_20200628_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='intro',
            field=models.TextField(verbose_name='intro'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='practical',
            field=models.TextField(verbose_name='practical'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='short',
            field=models.TextField(max_length=150, verbose_name='short'),
        ),
    ]
