# Generated by Django 4.1.4 on 2023-03-23 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0019_auto_20201003_1036"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NeighboringActivity",
        ),
    ]
