# Generated by Django 2.1.2 on 2018-12-12 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=40, verbose_name='f_name')),
                ('l_name', models.CharField(max_length=40, verbose_name='l_name')),
                ('street', models.CharField(blank=True, max_length=40, verbose_name='street')),
                ('number', models.CharField(blank=True, max_length=40, verbose_name='number')),
                ('municipality', models.CharField(blank=True, max_length=40, verbose_name='municipality')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='phone')),
            ],
            options={
                'verbose_name_plural': 'owners',
                'verbose_name': 'owner',
            },
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.Owner', verbose_name='owner')),
            ],
            options={
                'verbose_name_plural': 'ownerships',
                'verbose_name': 'ownership',
            },
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('oidn', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'parcels',
                'verbose_name': 'parcel',
            },
        ),
        migrations.AddField(
            model_name='ownership',
            name='parcel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.Parcel', verbose_name='parcel'),
        ),
    ]
