# Generated by Django 2.1.2 on 2018-12-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='owners',
            field=models.ManyToManyField(through='register.Ownership', to='register.Owner'),
        ),
    ]
