# Generated by Django 2.2.5 on 2020-06-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='info',
            field=models.TextField(blank=True, verbose_name='information'),
        ),
    ]
