# Generated by Django 2.2.5 on 2020-10-03 08:36

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_parcel_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='info',
            field=djrichtextfield.models.RichTextField(blank=True, verbose_name='information'),
        ),
    ]
