# Generated by Django 2.1.1 on 2019-02-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_parcel_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='address',
            field=models.CharField(blank=True, max_length=80, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='owner',
            name='name',
            field=models.CharField(blank=True, max_length=80, verbose_name='name'),
        ),
    ]
