# Generated by Django 4.1.4 on 2023-10-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0004_auto_20210207_1150"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcel",
            name="renters",
            field=models.ManyToManyField(related_name="rents", to="register.owner"),
        ),
    ]
