# Generated by Django 2.1.1 on 2019-02-04 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_parcel_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='key',
            field=models.CharField(max_length=17, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(17), django.core.validators.MaxLengthValidator(17)], verbose_name='key'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='oidn',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
