# Generated by Django 4.1.4 on 2023-10-06 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0005_parcel_renters"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parcel",
            name="renters",
        ),
    ]
