# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-18 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_auto_20170118_1556'),
        ('newsletter', '0004_auto_20170118_1531'),
    ]

    operations = [
    ]
