# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-17 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import magazine.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.IntegerField(choices=[(1, 'jan-feb-mrt'), (2, 'apr-mei-jun'), (3, 'jul-aug-sep'), (4, 'okt-nov-dec')], default=magazine.models.current_quarter)),
                ('file', models.FileField(upload_to='magazine')),
            ],
            options={
                'verbose_name': 'editie',
                'ordering': ['volume', '-quarter'],
                'verbose_name_plural': 'edities',
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=magazine.models.current_year)),
            ],
            options={
                'verbose_name': 'jaargang',
                'ordering': ['-year'],
                'verbose_name_plural': 'jaargangen',
            },
        ),
        migrations.AddField(
            model_name='edition',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='editions', to='magazine.Volume'),
        ),
    ]
