# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-18 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import magazine.models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edition',
            options={'ordering': ['volume', '-quarter'], 'verbose_name': 'edition', 'verbose_name_plural': 'editions'},
        ),
        migrations.AlterModelOptions(
            name='volume',
            options={'ordering': ['-year'], 'verbose_name': 'volume', 'verbose_name_plural': 'volumes'},
        ),
        migrations.AlterField(
            model_name='edition',
            name='file',
            field=models.FileField(upload_to=magazine.models.upload_to, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='quarter',
            field=models.IntegerField(choices=[(1, 'jan-feb-mrt'), (2, 'apr-mei-jun'), (3, 'jul-aug-sep'), (4, 'okt-nov-dec')], default=magazine.models.current_quarter, verbose_name='quarter'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='editions', to='magazine.Volume', verbose_name='volume'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='year',
            field=models.IntegerField(default=magazine.models.current_year, verbose_name='year'),
        ),
    ]
