# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-08 12:25
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('location', models.IntegerField(choices=[(1, 'Lembergestraat'), (2, 'Hoek ter Hulst')], verbose_name='location')),
                ('toads', models.IntegerField(default=0, verbose_name='toads')),
                ('frogs', models.IntegerField(default=0, verbose_name='frogs')),
                ('salamanders', models.IntegerField(default=0, verbose_name='salamanders')),
                ('toads_death', models.IntegerField(default=0, verbose_name='toads death')),
                ('frogs_death', models.IntegerField(default=0, verbose_name='frogs death')),
                ('salamanders_death', models.IntegerField(default=0, verbose_name='salamanders death')),
                ('remark', models.TextField(blank=True, default='', verbose_name='remark')),
            ],
            options={
                'verbose_name_plural': 'inputs',
                'verbose_name': 'input',
            },
        ),
        migrations.CreateModel(
            name='AmphibianTransferUser',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='input',
            name='by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='by'),
        ),
    ]
