# Generated by Django 3.1.4 on 2021-02-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amphi', '0004_auto_20170321_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='location',
            field=models.IntegerField(choices=[(1, 'Lembergestraat'), (2, 'Hoek ter Hulst'), (3, 'Hoek ter Hulst')], verbose_name='location'),
        ),
    ]
